---
title: "Introduction to the OikScrambling package"
author: 
 - "Charles Plessy"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Introduction to the OikScrambling package}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

# Introduction

This package contains a collection of vignettes to perform the analysis of
pairwise genome alignments between _Oikopleura_ genomes.

The core functions used here are maintained in our _GenomicBreaks_ R package,
which is fully documented at: <https://oist.github.io/GenomicBreaks>.

# How to build this site

As some of the computations take time, we build the vignettes on OIST's HPC
cluster _Deigo_ using the `?pkgdown::build_site` function, in a Git clone in a
subdirectory of the `/flash` filesystem.

```
singularity exec /apps/unit/BioinfoUgrp/Other/RStudio_server/2023.09.0-463/RStudio_server Rscript -e "pkgdown::build_site(devel=TRUE, lazy=TRUE)"
```

# How to install or update the necessary packages

## OikScrambling and GenomicBreaks

Sometimes it is necessary to upgrade the _OikScrambling_ package; this is done with:

```
singularity exec /apps/unit/BioinfoUgrp/Other/RStudio_server/2023.09.0-463/RStudio_server R CMD INSTALL .
```

And before, it may be needed to update `GenomicBreaks` or `BreakpointsData`:

```
singularity exec /apps/unit/BioinfoUgrp/Other/RStudio_server/2023.09.0-463/RStudio_server Rscript -e "remotes::install_github('oist/GenomicBreaks', repos=BiocManager::repositories())"
singularity exec /apps/unit/BioinfoUgrp/Other/RStudio_server/2023.09.0-463/RStudio_server Rscript -e "install.packages('BreakpointsData', repos='https://oist.github.io/plessy_oikgenomes_drat/')"
```

The trick is that the `GenomicBreaks` singularity images are hardcoded to
install new packages in `R/library/GBreaks_singularity`, which bypasses the
the problem that the images are read-only.

Command to recompute the `BreakPoints.Rdata` file

```
srun -pcompute -c8 --mem 300G --pty singularity exec /apps/unit/BioinfoUgrp/Other/RStudio_server/2023.09.0-463/RStudio_server Rscript -e "pkgdown::build_article('LoadGenomicBreaks')"
```

Commands to rebuild the whole site.

```
srun -pcompute -c8 --mem 300G --pty singularity exec /apps/unit/BioinfoUgrp/Other/RStudio_server/2023.09.0-463/RStudio_server Rscript -e "pkgdown::build_site(devel=TRUE, lazy=TRUE)"
srun -pcompute -c8 --mem 300G --pty singularity exec /apps/unit/BioinfoUgrp/Other/RStudio_server/2023.09.0-463/RStudio_server Rscript -e "pkgdown::build_site()"
```

## Data packages

### BSgenome packages

We need the sequences of the studied genomes.  They are provided in a _drat_
repository: <https://oist.github.io/plessy_oikgenomes_drat/>.

Example command to install one _Oikopleura_ BSgenome package if you do not yet
have it:

```
singularity exec /apps/unit/BioinfoUgrp/Other/RStudio_server/2023.09.0-463/RStudio_server Rscript -e "install.packages('BSgenome.Oidioi.OIST.OKI2018.I69', repos='https://oist.github.io/plessy_oikgenomes_drat/')"
```

### Genome annotations

The annotations from `/bucket/LuscombeU/common/Breakpoints/Annotations` are
distributed in the same drat repository as the alignment data.

```
install.packages('BreakpointsData', repos='https://oist.github.io/plessy_oikgenomes_drat/')
```
