#' Scaffolding guides
#'
#' This object is generated by the vignettes `AomScaffolding.Rmd`,
#' `KumeScaffolding.Rmd`, and `BergenScaffolding.Rmd`.  It contains _guide_ data
#' for the function [`GenomicBreaks::scaffoldByFlipAndMerge`].
#'
"scafs"
